services:
  UPMS_api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Auth__Mode=None
      - UPMS_CONNECTION_STRING=Host=UPMS_db;Port=5432;Database=upms;Username=upms;Password=upms
      - UPMS_ARTIFACTS_ROOT=/var/lib/upms
    ports:
      - "8081:8080"

  UPMS_worker:
    environment:
      - UPMS_CONNECTION_STRING=Host=UPMS_db;Port=5432;Database=upms;Username=upms;Password=upms
      - UPMS_ARTIFACTS_ROOT=/var/lib/upms

  UPMS_frontend:
    ports:
      - "8080:80"

  UPMS_db:
    environment:
      - POSTGRES_USER=upms
      - POSTGRES_PASSWORD=upms
      - POSTGRES_DB=upms
