services:
  UPMS_web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - UPMS_CONNECTION_STRING=Host=UPMS_db;Port=5432;Database=upms;Username=upms;Password=upms
    ports:
      - "8081:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  UPMS_db:
    environment:
      POSTGRES_USER: upms1
      POSTGRES_PASSWORD: upms
      POSTGRES_DB: upms


  UPMS_db_test:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: upms
      POSTGRES_PASSWORD: upms_test
      POSTGRES_DB: upms_test
    ports:
        - "5433:5432"  # Uncomment to expose test DB for local admin/debug
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U upms -d upms_test"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  pgdata:
  pgdata_test:
