// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UPMS.Data;
using UPMS.Data.ReadModels;

#nullable disable

namespace UPMS.Data.Migrations
{
    [DbContext(typeof(UpmsDbContext))]
    [Migration("20260308000100_CanonicalFieldRegistryAndFieldChangeNames")]
    partial class CanonicalFieldRegistryAndFieldChangeNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity<Snapshot>(e =>
            {
                e.ToTable("raw_snapshot");
                e.HasKey(x => x.Id);
                e.Property(x => x.Id).HasColumnName("id").HasColumnType("uuid").ValueGeneratedOnAdd();
                e.Property(x => x.ItsmSource).HasColumnName("itsm_source").HasColumnType("varchar(100)").IsRequired();
                e.Property(x => x.SnapshotDate).HasColumnName("snapshot_date").HasColumnType("timestamptz").IsRequired();
                e.Property(x => x.UploadedBy).HasColumnName("uploaded_by").HasColumnType("varchar(255)").IsRequired();
                e.Property(x => x.UploadedAt).HasColumnName("uploaded_at").HasColumnType("timestamptz").IsRequired();
                e.Property(x => x.UploadMetadata).HasColumnName("upload_metadata").HasColumnType("text").IsRequired(false);
            });

            modelBuilder.Entity<SnapshotTicket>(e =>
            {
                e.ToTable("snapshot_ticket");
                e.HasKey(x => x.Id);
                e.Property(x => x.Id).HasColumnName("id").HasColumnType("uuid").ValueGeneratedOnAdd();
                e.Property(x => x.SnapshotId).HasColumnName("snapshot_id").HasColumnType("uuid").IsRequired();
                e.Property(x => x.CompanyName).HasColumnName("company_name").HasColumnType("varchar(255)").IsRequired();
                e.Property(x => x.TicketKey).HasColumnName("ticket_key").HasColumnType("varchar(255)").IsRequired();

                e.HasIndex(x => new { x.SnapshotId, x.TicketKey }).IsUnique();

                e.HasOne(x => x.Snapshot)
                    .WithMany()
                    .HasForeignKey(x => x.SnapshotId)
                    .HasConstraintName("fk_snapshot_ticket_snapshot_id")
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity<FieldChange>(e =>
            {
                e.ToTable("field_change");
                e.HasKey(x => x.Id);

                var idBuilder = e.Property(x => x.Id)
                    .HasColumnName("id")
                    .HasColumnType("bigint")
                    .ValueGeneratedOnAdd();
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(idBuilder);

                e.Property(x => x.CompanyName).HasColumnName("company_name").HasColumnType("varchar(255)").IsRequired();
                e.Property(x => x.TicketKey).HasColumnName("ticket_key").HasColumnType("varchar(255)").IsRequired();
                e.Property(x => x.FieldName).HasColumnName("field_name").HasColumnType("varchar(255)").IsRequired();
                e.Property(x => x.CanonicalFieldName).HasColumnName("canonical_field_name").HasColumnType("varchar(255)").IsRequired(false);
                e.Property(x => x.FieldValue).HasColumnName("field_value").HasColumnType("text").IsRequired(false);
                e.Property(x => x.ObservedAt).HasColumnName("observed_at").HasColumnType("timestamptz").IsRequired();
                e.Property(x => x.SnapshotId).HasColumnName("snapshot_id").HasColumnType("uuid").IsRequired();

                e.HasOne<Snapshot>()
                    .WithMany()
                    .HasForeignKey(x => x.SnapshotId)
                    .HasConstraintName("fk_field_change_snapshot_id")
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity<ItsmSource>(e =>
            {
                e.ToTable("itsm_source");
                e.HasKey(x => x.Id);

                var idBuilder = e.Property(x => x.Id)
                    .HasColumnName("id")
                    .HasColumnType("integer")
                    .ValueGeneratedOnAdd();
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(idBuilder);

                e.Property(x => x.Name).HasColumnName("name").HasColumnType("text").IsRequired();
                e.Property(x => x.DisplayLabel).HasColumnName("display_label").HasColumnType("text").IsRequired();

                e.HasIndex(x => x.Name).IsUnique();
            });

            modelBuilder.Entity<ItsmFieldMapping>(e =>
            {
                e.ToTable("itsm_field_mapping");
                e.HasKey(x => new { x.ItsmSource, x.SourceFieldName });
                e.Property(x => x.ItsmSource).HasColumnName("itsm_source").HasColumnType("varchar(100)").IsRequired();
                e.Property(x => x.SourceFieldName).HasColumnName("source_field_name").HasColumnType("varchar(255)").IsRequired();
                e.Property(x => x.CanonicalFieldName).HasColumnName("canonical_field_name").HasColumnType("varchar(255)").IsRequired();
                e.Property(x => x.IsRequired).HasColumnName("is_required").HasColumnType("boolean").HasDefaultValue(false);
            });

            modelBuilder.Entity<CanonicalFieldDefinition>(e =>
            {
                e.ToTable("canonical_field_definition");
                e.HasKey(x => x.Name);
                e.Property(x => x.Name).HasColumnName("name").HasColumnType("varchar(255)").IsRequired();
                e.Property(x => x.DataType).HasColumnName("data_type").HasColumnType("varchar(50)").HasConversion<string>().IsRequired();
                e.Property(x => x.IsSystemRequired).HasColumnName("is_system_required").HasColumnType("boolean").HasDefaultValue(false);
            });

            modelBuilder.Entity<TicketFieldAtTimeDto>(e =>
            {
                e.HasNoKey();
                e.ToTable("TicketFieldAtTimeResults");
                e.Property(x => x.FieldName).HasColumnName("field_name");
                e.Property(x => x.FieldValue).HasColumnName("field_value");
                e.Property(x => x.ObservedAt).HasColumnName("observed_at");
            });

            modelBuilder.Entity<TicketFieldWithMetadataDto>(e =>
            {
                e.HasNoKey();
                e.ToTable("TicketFieldWithMetadataResults");
                e.Property(x => x.FieldName).HasColumnName("field_name");
                e.Property(x => x.FieldValue).HasColumnName("field_value");
                e.Property(x => x.ObservedAt).HasColumnName("observed_at");
                e.Property(x => x.SnapshotId).HasColumnName("snapshot_id");
            });

            modelBuilder.Entity<SnapshotTicketKeyDto>(e =>
            {
                e.HasNoKey();
                e.ToTable("SnapshotTicketKeyResults");
                e.Property(x => x.TicketKey).HasColumnName("ticket_key");
            });

            modelBuilder.Entity<SnapshotTicketPairDto>(e =>
            {
                e.HasNoKey();
                e.ToTable("SnapshotTicketPairResults");
                e.Property(x => x.SnapshotId).HasColumnName("snapshot_id");
                e.Property(x => x.TicketKey).HasColumnName("ticket_key");
            });

            modelBuilder.Entity<ReconstructedFieldDto>(e =>
            {
                e.HasNoKey();
                e.ToTable("ReconstructedFieldResults");
                e.Property(x => x.TicketKey).HasColumnName("ticket_key");
                e.Property(x => x.FieldName).HasColumnName("field_name");
                e.Property(x => x.FieldValue).HasColumnName("field_value");
            });
#pragma warning restore 612, 618
        }
    }
}
