// <auto-generated />
#nullable enable
namespace UPMS.Data.Migrations;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UPMS.Data;

[DbContext(typeof(UpmsDbContext))]
[Migration("20260301000001_InitialSchema")]
partial class InitialSchema
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        // raw_snapshot
        modelBuilder.Entity("UPMS.Data.Snapshot", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<string>("ItsmSource")
                .IsRequired()
                .HasColumnType("varchar(100)")
                .HasColumnName("itsm_source");

            b.Property<DateTimeOffset>("SnapshotDate")
                .HasColumnType("timestamptz")
                .HasColumnName("snapshot_date");

            b.Property<string>("UploadedBy")
                .IsRequired()
                .HasColumnType("varchar(255)")
                .HasColumnName("uploaded_by");

            b.Property<DateTimeOffset>("UploadedAt")
                .HasColumnType("timestamptz")
                .HasColumnName("uploaded_at");

            b.Property<string?>("UploadMetadata")
                .HasColumnType("text")
                .HasColumnName("upload_metadata");

            b.HasKey("Id");

            b.ToTable("raw_snapshot");
        });

        // snapshot_ticket
        modelBuilder.Entity("UPMS.Data.SnapshotTicket", b =>
        {
            b.Property<Guid>("Id")
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<Guid>("SnapshotId")
                .HasColumnType("uuid")
                .HasColumnName("snapshot_id");

            b.Property<string>("CompanyName")
                .IsRequired()
                .HasColumnType("varchar(255)")
                .HasColumnName("company_name");

            b.Property<string>("TicketKey")
                .IsRequired()
                .HasColumnType("varchar(255)")
                .HasColumnName("ticket_key");

            b.HasKey("Id");

            b.HasIndex(new[] { "SnapshotId", "TicketKey" }, "IX_snapshot_ticket_snapshot_id_ticket_key")
                .IsUnique();

            b.ToTable("snapshot_ticket");
        });

        // field_change
        modelBuilder.Entity("UPMS.Data.FieldChange", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("bigint")
                .HasColumnName("id")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

            b.Property<string>("CompanyName")
                .IsRequired()
                .HasColumnType("varchar(255)")
                .HasColumnName("company_name");

            b.Property<string>("TicketKey")
                .IsRequired()
                .HasColumnType("varchar(255)")
                .HasColumnName("ticket_key");

            b.Property<string>("FieldName")
                .IsRequired()
                .HasColumnType("varchar(255)")
                .HasColumnName("field_name");

            b.Property<string?>("FieldValue")
                .HasColumnType("text")
                .HasColumnName("field_value");

            b.Property<DateTimeOffset>("ObservedAt")
                .HasColumnType("timestamptz")
                .HasColumnName("observed_at");

            b.Property<Guid>("SnapshotId")
                .HasColumnType("uuid")
                .HasColumnName("snapshot_id");

            b.HasKey("Id");

            b.HasIndex("SnapshotId");
            b.HasIndex(new[] { "CompanyName", "TicketKey" });
            b.HasIndex("ObservedAt");

            b.ToTable("field_change");
        });

        // itsm_source
        modelBuilder.Entity("UPMS.Data.ItsmSource", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasColumnName("id")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

            b.Property<string>("Name")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("name");

            b.Property<string>("DisplayLabel")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("display_label");

            b.HasKey("Id");

            b.HasIndex("Name").IsUnique();

            b.ToTable("itsm_source");
        });

        // itsm_field_mapping
        modelBuilder.Entity("UPMS.Data.ItsmFieldMapping", b =>
        {
            b.Property<string>("ItsmSource")
                .IsRequired()
                .HasColumnType("varchar(100)")
                .HasColumnName("itsm_source");

            b.Property<string>("SourceFieldName")
                .IsRequired()
                .HasColumnType("varchar(255)")
                .HasColumnName("source_field_name");

            b.Property<string>("CanonicalFieldName")
                .IsRequired()
                .HasColumnType("varchar(255)")
                .HasColumnName("canonical_field_name");

            b.Property<bool>("IsRequired")
                .HasDefaultValue(false)
                .HasColumnType("boolean")
                .HasColumnName("is_required");

            b.HasKey("ItsmSource", "SourceFieldName");

            b.ToTable("itsm_field_mapping");
        });

        // Keyless DTOs
        modelBuilder.Entity("UPMS.Data.ReadModels.TicketFieldAtTimeDto", b =>
        {
            b.Property<string>("FieldName").HasColumnName("field_name");
            b.Property<string?>("FieldValue").HasColumnName("field_value");
            b.Property<DateTimeOffset>("ObservedAt").HasColumnName("observed_at");
            b.HasNoKey();
        });

        modelBuilder.Entity("UPMS.Data.ReadModels.TicketFieldWithMetadataDto", b =>
        {
            b.Property<string>("FieldName").HasColumnName("field_name");
            b.Property<string?>("FieldValue").HasColumnName("field_value");
            b.Property<DateTimeOffset>("ObservedAt").HasColumnName("observed_at");
            b.Property<Guid>("SnapshotId").HasColumnName("snapshot_id");
            b.HasNoKey();
        });

        modelBuilder.Entity("UPMS.Data.ReadModels.SnapshotTicketKeyDto", b =>
        {
            b.Property<string>("TicketKey").HasColumnName("ticket_key");
            b.HasNoKey();
        });

        modelBuilder.Entity("UPMS.Data.ReadModels.SnapshotTicketPairDto", b =>
        {
            b.Property<Guid>("SnapshotId").HasColumnName("snapshot_id");
            b.Property<string>("TicketKey").HasColumnName("ticket_key");
            b.HasNoKey();
        });

        modelBuilder.Entity("UPMS.Data.ReadModels.ReconstructedFieldDto", b =>
        {
            b.Property<string>("TicketKey").HasColumnName("ticket_key");
            b.Property<string>("FieldName").HasColumnName("field_name");
            b.Property<string?>("FieldValue").HasColumnName("field_value");
            b.HasNoKey();
        });

        // FK relationships
        modelBuilder.Entity("UPMS.Data.SnapshotTicket", b =>
        {
            b.HasOne("UPMS.Data.Snapshot", "Snapshot")
                .WithMany()
                .HasForeignKey("SnapshotId")
                .HasConstraintName("fk_snapshot_ticket_snapshot_id")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Snapshot");
        });

        modelBuilder.Entity("UPMS.Data.FieldChange", b =>
        {
            b.HasOne("UPMS.Data.Snapshot", null)
                .WithMany()
                .HasForeignKey("SnapshotId")
                .HasConstraintName("fk_field_change_snapshot_id")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });
#pragma warning restore 612, 618
    }
}
