// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UPMS.Data;

#nullable disable

namespace UPMS.Data.Migrations
{
    [DbContext(typeof(UpmsDbContext))]
    partial class UpmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UPMS.Data.CanonicalFieldDefinition", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<CanonicalFieldDataType>("DataType")
                        .HasConversion<string>()
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("data_type");

                    b.Property<bool>("IsSystemRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system_required");

                    b.HasKey("Name");

                    b.ToTable("canonical_field_definition", (string)null);
                });

            modelBuilder.Entity("UPMS.Data.FieldChange", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CanonicalFieldName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("canonical_field_name");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("field_name");

                    b.Property<string>("FieldValue")
                        .HasColumnType("text")
                        .HasColumnName("field_value");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("observed_at");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("TicketKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ticket_key");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("field_change", (string)null);
                });

            modelBuilder.Entity("UPMS.Data.ItsmFieldMapping", b =>
                {
                    b.Property<string>("ItsmSource")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("itsm_source");

                    b.Property<string>("SourceFieldName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("source_field_name");

                    b.Property<string>("CanonicalFieldName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("canonical_field_name");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_required");

                    b.HasKey("ItsmSource", "SourceFieldName");

                    b.ToTable("itsm_field_mapping", (string)null);
                });

            modelBuilder.Entity("UPMS.Data.ItsmSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("itsm_source", (string)null);
                });

            modelBuilder.Entity("UPMS.Data.Jobs.BackgroundJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedNever()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("job_type");

                    b.Property<DateTime?>("LeaseExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("LeaseOwner")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("lease_owner");

                    b.Property<string>("OutputContentType")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("output_content_type");

                    b.Property<string>("OutputFileName")
                        .HasColumnType("varchar(512)")
                        .HasColumnName("output_file_name");

                    b.Property<string>("OutputFilePath")
                        .HasColumnType("text")
                        .HasColumnName("output_file_path");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<string>("RequestedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("requested_by");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text")
                        .HasColumnName("result_json");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("JobType", "Status", "CreatedAt")
                        .HasDatabaseName("ix_background_job_job_type_status_created_at");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_background_job_status_created_at");

                    b.ToTable("background_job", (string)null);
                });

            modelBuilder.Entity("UPMS.Data.ProblemRequests.ProblemRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedNever()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Assignee")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("assignee");

                    b.Property<string>("CompanyName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DecisionReason")
                        .HasColumnType("text")
                        .HasColumnName("decision_reason");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ItsmSource")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("itsm_source");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("justification");

                    b.Property<DateTime?>("LinkedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("linked_at");

                    b.Property<string>("ProblemCompanyName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("problem_company_name");

                    b.Property<string>("ProblemItsmSource")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("problem_itsm_source");

                    b.Property<string>("ProblemReference")
                        .HasColumnType("varchar(512)")
                        .HasColumnName("problem_reference");

                    b.Property<string>("ProblemTicketKey")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("problem_ticket_key");

                    b.Property<string>("RequesterEmail")
                        .HasColumnType("varchar(320)")
                        .HasColumnName("requester_email");

                    b.Property<string>("RequesterName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("requester_name");

                    b.Property<string>("RequesterTeam")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("requester_team");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Assignee")
                        .HasDatabaseName("ix_problem_request_assignee");

                    b.HasIndex("CompanyName", "ItsmSource")
                        .HasDatabaseName("ix_problem_request_company_source");

                    b.HasIndex("Status", "UpdatedAt")
                        .HasDatabaseName("ix_problem_request_status_updated_at");

                    b.ToTable("problem_request", (string)null);
                });

            modelBuilder.Entity("UPMS.Data.ProblemRequests.ProblemRequestComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedNever()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("author_name");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment_text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProblemRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_request_id");

                    b.HasKey("Id");

                    b.HasIndex("ProblemRequestId", "CreatedAt")
                        .HasDatabaseName("ix_problem_request_comment_request_created_at");

                    b.ToTable("problem_request_comment", (string)null);
                });

            modelBuilder.Entity("UPMS.Data.ReadModels.ReconstructedFieldDto", b =>
                {
                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<string>("FieldValue")
                        .HasColumnType("text")
                        .HasColumnName("field_value");

                    b.Property<string>("TicketKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticket_key");

                    b.HasNoKey();

                    b.ToTable("ReconstructedFieldResults");
                });

            modelBuilder.Entity("UPMS.Data.ReadModels.SnapshotTicketKeyDto", b =>
                {
                    b.Property<string>("TicketKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticket_key");

                    b.HasNoKey();

                    b.ToTable("SnapshotTicketKeyResults");
                });

            modelBuilder.Entity("UPMS.Data.ReadModels.SnapshotTicketPairDto", b =>
                {
                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("TicketKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticket_key");

                    b.HasNoKey();

                    b.ToTable("SnapshotTicketPairResults");
                });

            modelBuilder.Entity("UPMS.Data.ReadModels.TicketFieldAtTimeDto", b =>
                {
                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<string>("FieldValue")
                        .HasColumnType("text")
                        .HasColumnName("field_value");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.HasNoKey();

                    b.ToTable("TicketFieldAtTimeResults");
                });

            modelBuilder.Entity("UPMS.Data.ReadModels.TicketFieldWithMetadataDto", b =>
                {
                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<string>("FieldValue")
                        .HasColumnType("text")
                        .HasColumnName("field_value");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.HasNoKey();

                    b.ToTable("TicketFieldWithMetadataResults");
                });

            modelBuilder.Entity("UPMS.Data.Snapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ItsmSource")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("itsm_source");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("snapshot_date");

                    b.Property<string>("UploadMetadata")
                        .HasColumnType("text")
                        .HasColumnName("upload_metadata");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.ToTable("raw_snapshot", (string)null);
                });

            modelBuilder.Entity("UPMS.Data.SnapshotTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("company_name");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("TicketKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ticket_key");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "TicketKey")
                        .IsUnique();

                    b.ToTable("snapshot_ticket", (string)null);
                });

            modelBuilder.Entity("UPMS.Data.FieldChange", b =>
                {
                    b.HasOne("UPMS.Data.Snapshot", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_field_change_snapshot_id");
                });

            modelBuilder.Entity("UPMS.Data.ProblemRequests.ProblemRequestComment", b =>
                {
                    b.HasOne("UPMS.Data.ProblemRequests.ProblemRequest", "ProblemRequest")
                        .WithMany("Comments")
                        .HasForeignKey("ProblemRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_request_comment_request_id");

                    b.Navigation("ProblemRequest");
                });

            modelBuilder.Entity("UPMS.Data.ProblemRequests.ProblemRequest", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("UPMS.Data.SnapshotTicket", b =>
                {
                    b.HasOne("UPMS.Data.Snapshot", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_snapshot_ticket_snapshot_id");

                    b.Navigation("Snapshot");
                });
#pragma warning restore 612, 618
        }
    }
}
