// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UPMS.Data;

#nullable disable

namespace UPMS.Data.Migrations
{
    [DbContext(typeof(UpmsDbContext))]
    partial class UpmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UPMS.Data.FieldChange", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("field_name");

                    b.Property<string>("FieldValue")
                        .HasColumnType("text")
                        .HasColumnName("field_value");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("observed_at");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("TicketKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ticket_key");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("field_change", (string)null);
                });

            modelBuilder.Entity("UPMS.Data.ItsmFieldMapping", b =>
                {
                    b.Property<string>("ItsmSource")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("itsm_source");

                    b.Property<string>("SourceFieldName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("source_field_name");

                    b.Property<string>("CanonicalFieldName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("canonical_field_name");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_required");

                    b.HasKey("ItsmSource", "SourceFieldName");

                    b.ToTable("itsm_field_mapping", (string)null);
                });

            modelBuilder.Entity("UPMS.Data.ItsmSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("itsm_source", (string)null);
                });

            modelBuilder.Entity("UPMS.Data.ReadModels.ReconstructedFieldDto", b =>
                {
                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<string>("FieldValue")
                        .HasColumnType("text")
                        .HasColumnName("field_value");

                    b.Property<string>("TicketKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticket_key");

                    b.ToTable("ReconstructedFieldResults");
                });

            modelBuilder.Entity("UPMS.Data.ReadModels.SnapshotTicketKeyDto", b =>
                {
                    b.Property<string>("TicketKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticket_key");

                    b.ToTable("SnapshotTicketKeyResults");
                });

            modelBuilder.Entity("UPMS.Data.ReadModels.SnapshotTicketPairDto", b =>
                {
                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("TicketKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticket_key");

                    b.ToTable("SnapshotTicketPairResults");
                });

            modelBuilder.Entity("UPMS.Data.ReadModels.TicketFieldAtTimeDto", b =>
                {
                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<string>("FieldValue")
                        .HasColumnType("text")
                        .HasColumnName("field_value");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.ToTable("TicketFieldAtTimeResults");
                });

            modelBuilder.Entity("UPMS.Data.ReadModels.TicketFieldWithMetadataDto", b =>
                {
                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<string>("FieldValue")
                        .HasColumnType("text")
                        .HasColumnName("field_value");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.ToTable("TicketFieldWithMetadataResults");
                });

            modelBuilder.Entity("UPMS.Data.Snapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ItsmSource")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("itsm_source");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("snapshot_date");

                    b.Property<string>("UploadMetadata")
                        .HasColumnType("text")
                        .HasColumnName("upload_metadata");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.ToTable("raw_snapshot", (string)null);
                });

            modelBuilder.Entity("UPMS.Data.SnapshotTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("company_name");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("TicketKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ticket_key");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "TicketKey")
                        .IsUnique();

                    b.ToTable("snapshot_ticket", (string)null);
                });

            modelBuilder.Entity("UPMS.Data.FieldChange", b =>
                {
                    b.HasOne("UPMS.Data.Snapshot", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_field_change_snapshot_id");
                });

            modelBuilder.Entity("UPMS.Data.SnapshotTicket", b =>
                {
                    b.HasOne("UPMS.Data.Snapshot", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_snapshot_ticket_snapshot_id");

                    b.Navigation("Snapshot");
                });
#pragma warning restore 612, 618
        }
    }
}
