// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UPMS.Data;

#nullable disable

namespace UPMS.Data.Migrations
{
    [DbContext(typeof(UpmsDbContext))]
    partial class UpmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UPMS.Data.CanonicalFieldDefinition", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<CanonicalFieldDataType>("DataType")
                        .HasConversion<string>()
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("data_type");

                    b.Property<bool>("IsSystemRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system_required");

                    b.HasKey("Name");

                    b.ToTable("canonical_field_definition", (string)null);
                });

            modelBuilder.Entity("UPMS.Data.FieldChange", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CanonicalFieldName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("canonical_field_name");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("field_name");

                    b.Property<string>("FieldValue")
                        .HasColumnType("text")
                        .HasColumnName("field_value");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("observed_at");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("TicketKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ticket_key");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("field_change", (string)null);
                });

            modelBuilder.Entity("UPMS.Data.ItsmFieldMapping", b =>
                {
                    b.Property<string>("ItsmSource")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("itsm_source");

                    b.Property<string>("SourceFieldName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("source_field_name");

                    b.Property<string>("CanonicalFieldName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("canonical_field_name");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_required");

                    b.HasKey("ItsmSource", "SourceFieldName");

                    b.ToTable("itsm_field_mapping", (string)null);
                });

            modelBuilder.Entity("UPMS.Data.ItsmSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("itsm_source", (string)null);
                });

            modelBuilder.Entity("UPMS.Data.FileSharePollingSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedNever()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArchivePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("archive_path");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_job_id");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<string>("ErrorPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error_path");

                    b.Property<string>("FilePatternsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_patterns_json");

                    b.Property<bool>("IsSystemManaged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system_managed");

                    b.Property<string>("ItsmSource")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("itsm_source");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<Guid?>("LastJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_job_id");

                    b.Property<DateTime?>("LastRunCompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_run_completed_at");

                    b.Property<DateTime?>("LastRunStartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_run_started_at");

                    b.Property<DateTime?>("LastSucceededAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_succeeded_at");

                    b.Property<int?>("MaxFilesPerCycle")
                        .HasColumnType("integer")
                        .HasColumnName("max_files_per_cycle");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("NextPollDueAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("next_poll_due_at");

                    b.Property<int>("PollIntervalSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(300)
                        .HasColumnName("poll_interval_seconds");

                    b.Property<int>("StableFileAgeSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("stable_file_age_seconds");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("WatchedPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("watched_path");

                    b.HasKey("Id");

                    b.HasIndex("CurrentJobId")
                        .HasDatabaseName("ix_file_share_polling_source_current_job_id");

                    b.HasIndex("Enabled", "NextPollDueAt")
                        .HasDatabaseName("ix_file_share_polling_source_enabled_due_at");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_file_share_polling_source_name");

                    b.HasIndex("WatchedPath")
                        .IsUnique()
                        .HasDatabaseName("ix_file_share_polling_source_watched_path");

                    b.ToTable("file_share_polling_source", (string)null);
                });

            modelBuilder.Entity("UPMS.Data.Jobs.BackgroundJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedNever()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("job_type");

                    b.Property<DateTime?>("LeaseExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("LeaseOwner")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("lease_owner");

                    b.Property<string>("OutputContentType")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("output_content_type");

                    b.Property<string>("OutputFileName")
                        .HasColumnType("varchar(512)")
                        .HasColumnName("output_file_name");

                    b.Property<string>("OutputFilePath")
                        .HasColumnType("text")
                        .HasColumnName("output_file_path");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<string>("RequestedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("requested_by");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text")
                        .HasColumnName("result_json");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("JobType", "Status", "CreatedAt")
                        .HasDatabaseName("ix_background_job_job_type_status_created_at");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_background_job_status_created_at");

                    b.ToTable("background_job", (string)null);
                });

            modelBuilder.Entity("UPMS.Data.Delivery.CompanyProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedNever()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("company_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("display_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_company_profile_company_key");

                    b.HasIndex("DisplayName")
                        .HasDatabaseName("ix_company_profile_display_name");

                    b.ToTable("company_profile", (string)null);
                });

            modelBuilder.Entity("UPMS.Data.Delivery.DistributionList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedNever()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_profile_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CompanyProfileId", "IsActive", "Name")
                        .HasDatabaseName("ix_distribution_list_company_profile_id_is_active_name");

                    b.HasIndex("CompanyProfileId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_distribution_list_company_profile_id_name");

                    b.ToTable("distribution_list", (string)null);
                });

            modelBuilder.Entity("UPMS.Data.Delivery.DistributionListRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedNever()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("channel");

                    b.Property<string>("DisplayName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("DistributionListId")
                        .HasColumnType("uuid")
                        .HasColumnName("distribution_list_id");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("varchar(512)")
                        .HasColumnName("endpoint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text")
                        .HasColumnName("metadata_json");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DistributionListId", "Channel", "Endpoint")
                        .IsUnique()
                        .HasDatabaseName("ix_distribution_list_recipient_distribution_list_id_channel_endpoint");

                    b.HasIndex("DistributionListId", "IsActive", "SortOrder")
                        .HasDatabaseName("ix_distribution_list_recipient_distribution_list_id_is_active_sort_order");

                    b.ToTable("distribution_list_recipient", (string)null);
                });

            modelBuilder.Entity("UPMS.Data.Delivery.ReportDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedNever()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("ArtifactContentType")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("artifact_content_type");

                    b.Property<string>("ArtifactFileName")
                        .HasColumnType("varchar(512)")
                        .HasColumnName("artifact_file_name");

                    b.Property<string>("ArtifactPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("artifact_path");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<string>("CompanyDisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("company_display_name");

                    b.Property<Guid>("CompanyProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_profile_id");

                    b.Property<string>("CompanyKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("company_key");

                    b.Property<Guid>("DistributionListId")
                        .HasColumnType("uuid")
                        .HasColumnName("distribution_list_id");

                    b.Property<string>("DistributionListName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("distribution_list_name");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("last_error_message");

                    b.Property<DateTime?>("LastAttemptedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_attempted_at");

                    b.Property<Guid?>("LastBackgroundJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_background_job_id");

                    b.Property<int>("RecipientCount")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_count");

                    b.Property<string>("RecipientSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient_snapshot_json");

                    b.Property<Guid>("ReportJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_job_id");

                    b.Property<string>("RequestedBy")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("requested_by");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("varchar(512)")
                        .HasColumnName("subject");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyKey", "CreatedAt")
                        .HasDatabaseName("ix_report_delivery_company_key_created_at");

                    b.HasIndex("DistributionListId", "CreatedAt")
                        .HasDatabaseName("ix_report_delivery_distribution_list_id_created_at");

                    b.HasIndex("ReportJobId", "CreatedAt")
                        .HasDatabaseName("ix_report_delivery_report_job_id_created_at");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_report_delivery_status_created_at");

                    b.ToTable("report_delivery", (string)null);
                });

            modelBuilder.Entity("UPMS.Data.ReadModels.ReconstructedFieldDto", b =>
                {
                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<string>("FieldValue")
                        .HasColumnType("text")
                        .HasColumnName("field_value");

                    b.Property<string>("TicketKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticket_key");

                    b.HasNoKey();

                    b.ToTable("ReconstructedFieldResults");
                });

            modelBuilder.Entity("UPMS.Data.ReadModels.SnapshotTicketKeyDto", b =>
                {
                    b.Property<string>("TicketKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticket_key");

                    b.HasNoKey();

                    b.ToTable("SnapshotTicketKeyResults");
                });

            modelBuilder.Entity("UPMS.Data.ReadModels.SnapshotTicketPairDto", b =>
                {
                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("TicketKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticket_key");

                    b.HasNoKey();

                    b.ToTable("SnapshotTicketPairResults");
                });

            modelBuilder.Entity("UPMS.Data.ReadModels.TicketFieldAtTimeDto", b =>
                {
                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<string>("FieldValue")
                        .HasColumnType("text")
                        .HasColumnName("field_value");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.HasNoKey();

                    b.ToTable("TicketFieldAtTimeResults");
                });

            modelBuilder.Entity("UPMS.Data.ReadModels.TicketFieldWithMetadataDto", b =>
                {
                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<string>("FieldValue")
                        .HasColumnType("text")
                        .HasColumnName("field_value");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.HasNoKey();

                    b.ToTable("TicketFieldWithMetadataResults");
                });

            modelBuilder.Entity("UPMS.Data.Snapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ItsmSource")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("itsm_source");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("snapshot_date");

                    b.Property<string>("UploadMetadata")
                        .HasColumnType("text")
                        .HasColumnName("upload_metadata");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.ToTable("raw_snapshot", (string)null);
                });

            modelBuilder.Entity("UPMS.Data.SnapshotTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("company_name");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("TicketKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ticket_key");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "TicketKey")
                        .IsUnique();

                    b.ToTable("snapshot_ticket", (string)null);
                });

            modelBuilder.Entity("UPMS.Data.Delivery.DistributionList", b =>
                {
                    b.HasOne("UPMS.Data.Delivery.CompanyProfile", "CompanyProfile")
                        .WithMany("DistributionLists")
                        .HasForeignKey("CompanyProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_distribution_list_company_profile_id");

                    b.Navigation("CompanyProfile");
                });

            modelBuilder.Entity("UPMS.Data.Delivery.DistributionListRecipient", b =>
                {
                    b.HasOne("UPMS.Data.Delivery.DistributionList", "DistributionList")
                        .WithMany("Recipients")
                        .HasForeignKey("DistributionListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_distribution_list_recipient_distribution_list_id");

                    b.Navigation("DistributionList");
                });

            modelBuilder.Entity("UPMS.Data.Delivery.CompanyProfile", b =>
                {
                    b.Navigation("DistributionLists");
                });

            modelBuilder.Entity("UPMS.Data.Delivery.DistributionList", b =>
                {
                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("UPMS.Data.FieldChange", b =>
                {
                    b.HasOne("UPMS.Data.Snapshot", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_field_change_snapshot_id");
                });

            modelBuilder.Entity("UPMS.Data.SnapshotTicket", b =>
                {
                    b.HasOne("UPMS.Data.Snapshot", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_snapshot_ticket_snapshot_id");

                    b.Navigation("Snapshot");
                });
#pragma warning restore 612, 618
        }
    }
}
