namespace UPMS.Web.Plugins.Email;

using System.Text;
using UPMS.Data;
using UPMS.Web.Reporting;

/// <summary>
/// Renders pre-defined HTML email templates populated with ticket data.
/// </summary>
public static class EmailTemplateRenderer
{
    public const string TemplateSummary = "Monthly Summary";
    public const string TemplateEscalation = "Escalation Notice";

    public static string Render(
        string templateName,
        string company,
        string itsmSource,
        DateTime asOfDate,
        IReadOnlyList<Ticket> tickets)
    {
        return templateName switch
        {
            TemplateSummary => RenderSummary(company, itsmSource, asOfDate, tickets),
            TemplateEscalation => RenderEscalation(company, itsmSource, asOfDate, tickets),
            _ => throw new ArgumentException($"Unknown template: '{templateName}'. Available templates: {TemplateSummary}, {TemplateEscalation}", nameof(templateName))
        };
    }

    private static string RenderSummary(string company, string itsmSource, DateTime asOfDate, IReadOnlyList<Ticket> tickets)
    {
        int total = tickets.Count;
        int open = tickets.Count(t => IsState(t, "Open", "New"));
        int inProgress = tickets.Count(t => IsState(t, "In Progress"));
        int resolved = tickets.Count(t => IsState(t, "Resolved", "Closed"));

        StringBuilder rows = new();
        foreach (Ticket ticket in tickets.Take(20))
        {
            string status = TicketFieldHelpers.GetFieldValue(ticket, "State", fallback: "-");
            string priority = TicketFieldHelpers.GetFieldValue(ticket, "Priority", fallback: "-");
            rows.AppendLine($"<tr><td>{HtmlEncode(ticket.TicketKey)}</td><td>{HtmlEncode(status)}</td><td>{HtmlEncode(priority)}</td></tr>");
        }

        return $$"""
            <!DOCTYPE html>
            <html>
            <head><meta charset="utf-8"><title>Monthly Summary &#x2014; {{HtmlEncode(company)}}</title>
            <style>body{font-family:Arial,sans-serif;color:#333;max-width:800px;margin:0 auto;padding:20px}h1{color:#1a3c5e}table{width:100%;border-collapse:collapse}th,td{padding:8px;text-align:left;border-bottom:1px solid #ddd}th{background:#1a3c5e;color:white}.stat{display:inline-block;padding:10px 20px;margin:5px;background:#f0f4f8;border-radius:4px;text-align:center}.stat-number{font-size:2em;font-weight:bold;color:#1a3c5e}</style>
            </head>
            <body>
            <h1>Monthly Problem Management Summary</h1>
            <p><strong>Company:</strong> {{HtmlEncode(company)}} | <strong>Source:</strong> {{HtmlEncode(itsmSource.ToUpperInvariant())}} | <strong>As of:</strong> {{asOfDate:dd MMM yyyy}}</p>
            <div>
              <div class="stat"><div class="stat-number">{{total}}</div>Total Tickets</div>
              <div class="stat"><div class="stat-number">{{open}}</div>Open</div>
              <div class="stat"><div class="stat-number">{{inProgress}}</div>In Progress</div>
              <div class="stat"><div class="stat-number">{{resolved}}</div>Resolved</div>
            </div>
            <h2>Ticket Detail</h2>
            <table><thead><tr><th>Ticket Key</th><th>Status</th><th>Priority</th></tr></thead>
            <tbody>{{rows}}</tbody></table>
            <hr><p style="color:#999;font-size:0.8em">Generated by UPMS on {{DateTime.UtcNow:yyyy-MM-dd HH:mm}} UTC</p>
            </body></html>
            """;
    }

    private static string RenderEscalation(string company, string itsmSource, DateTime asOfDate, IReadOnlyList<Ticket> tickets)
    {
        List<Ticket> highPriority = tickets
            .Where(TicketFieldHelpers.IsHighPriority)
            .ToList();

        StringBuilder rows = new();
        foreach (Ticket ticket in highPriority.Take(10))
        {
            string status = TicketFieldHelpers.GetFieldValue(ticket, "State", fallback: "-");
            string priority = TicketFieldHelpers.GetFieldValue(ticket, "Priority", fallback: "-");
            string assignee = TicketFieldHelpers.GetFieldValue(ticket, "Assigned To", fallback: "Unassigned");
            rows.AppendLine($"<tr><td>{HtmlEncode(ticket.TicketKey)}</td><td>{HtmlEncode(status)}</td><td><strong>{HtmlEncode(priority)}</strong></td><td>{HtmlEncode(assignee)}</td></tr>");
        }

        return $$"""
            <!DOCTYPE html>
            <html>
            <head><meta charset="utf-8"><title>Escalation Notice &#x2014; {{HtmlEncode(company)}}</title>
            <style>body{font-family:Arial,sans-serif;color:#333;max-width:800px;margin:0 auto;padding:20px}h1{color:#c0392b}.alert{background:#fdf2f2;border-left:4px solid #c0392b;padding:15px;margin:20px 0}table{width:100%;border-collapse:collapse}th,td{padding:8px;text-align:left;border-bottom:1px solid #ddd}th{background:#c0392b;color:white}</style>
            </head>
            <body>
            <h1>&#x26A0; Escalation Notice</h1>
            <div class="alert"><strong>Action Required:</strong> {{highPriority.Count}} high-priority ticket(s) require immediate attention for <strong>{{HtmlEncode(company)}}</strong>.</div>
            <p><strong>Company:</strong> {{HtmlEncode(company)}} | <strong>Source:</strong> {{HtmlEncode(itsmSource.ToUpperInvariant())}} | <strong>As of:</strong> {{asOfDate:dd MMM yyyy}}</p>
            <h2>High Priority Tickets</h2>
            <table><thead><tr><th>Ticket Key</th><th>Status</th><th>Priority</th><th>Assignee</th></tr></thead>
            <tbody>{{rows}}</tbody></table>
            <hr><p style="color:#999;font-size:0.8em">Generated by UPMS on {{DateTime.UtcNow:yyyy-MM-dd HH:mm}} UTC</p>
            </body></html>
            """;
    }

    private static bool IsState(Ticket ticket, params string[] values)
    {
        var state = TicketFieldHelpers.GetFieldValue(ticket, "State", fallback: string.Empty);
        return values.Any(v => string.Equals(state, v, StringComparison.OrdinalIgnoreCase));
    }

    private static string HtmlEncode(string value) =>
        System.Net.WebUtility.HtmlEncode(value);
}
